### ISSUE TITLE
really coll Henrik 

### ISSUE THREAD

**Issue by screscencio** [hkniberg/wie#1]
Nice tool. Would be nice to add mapping capabilities to places.

**Comment by hkniberg** [comment]
You mean like "click on a place, and see where it is on a map"?

**Comment by screscencio** [comment]
Yes.

**Comment by screscencio** [comment]
Or show on a map where people are using their GPS location.

**Comment by hkniberg** [comment]
I actually implemented a "show people on a map using GPS" feature (check the commit history), but to everyone's surprise it wasn't as useful as we thought. The ski system was too big for a smartphone screen, so you either had to zoom out really far (so you can't recognize where people are anyway), or scroll around a lot which takes too long. Also, looking at a map it was to really understand where people are (too detailed). I want to know at one glance if my kid is in ski slope X or in the restaurant, not the exact GPS coordinate on the map. Plus, sending GPS updates in the background is a battery killer and introduces all kinds of phone-specific issues (such as iphone not allowing web pages to do background processing). So I removed the feature and went back to the simpler version.
