### ISSUE TITLE
Redirected to login page after deleting or renaming person

### ISSUE THREAD

**Issue by JHilmarch** [hkniberg/wie#2]
I´m beeing redirected to login page after deleting or renaming person. I´m using Internet Explorer 11.
![removingperson](https://cloud.githubusercontent.com/assets/808611/7301837/8130f534-e9e5-11e4-981e-3ec9c85b4f9a.png)

**Comment by hkniberg** [comment]
Hmmmm.... can't repeat the bug on Chrome or Firefox or Safari on Mac. So I'm closing this. Thx for reporting though.
